name: voila-gallery-country-indicators
channels:
- conda-forge
dependencies:
- jupyterlab>=3.1
- voila>=0.2.11
- ipywidgets>=8.0.3
- matplotlib>=3.7.1
- numpy>=1.24.3
- pandas>=1.5.3
- plotly>=5.9.0
- seaborn>=0.12.2
- IPython>=8.12.0
- jupyter_client>=7.4.1
- jupyter_core>=5.3.0
- jupyterlab>=3.6.3
- notebook>=6.5.4
